=== axelmate6/JD2018-12-10/src/by/it/kushnerov/jd02_07/users+att.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://jd02.kushnerov.by.it/somestring+att"
        xmlns:tag="http://jd02.kushnerov.by.it/somestring+att"
        elementFormDefault="qualified"
>
<element name="users" >
    <complexType>
        <sequence>
            <element
                    name="client"
                    type="tag:Client"
                    minOccurs="0"
                    maxOccurs="unbounded" >
            </element>
        </sequence>
    </complexType>
</element>

<complexType name="Client">
    <sequence>
        <element name="login" type="ID" />
        <element name="email" type="string" />
        <element name="password" type="string" />
        <element name="name" type="string"/>
        <element name="surname" type="string"/>
        <element name="phone" type="int"/>
        <element name="creditcard" type="int"/>
        <element name="bookings"  type="tag:Bookings"/>
    </sequence>
    <attribute name="nickname" type="string" use="required"/>
</complexType>

<complexType name="Bookings">
    <sequence>
        <element name="booking"
                 minOccurs="0"
                 maxOccurs="unbounded"
                 type="tag:Booking"/>
    </sequence>
    <attribute name="max" type="positiveInteger" use="required"/>
</complexType>

<complexType name="Booking">
    <sequence>
        <element name="description" type="string"/>
        <element name="floor" type="integer"/>
        <element name="rooms" type="positiveInteger"/>
        <element name="days" type="positiveInteger"/>
        <element name="price" type="double"/>
    </sequence>
</complexType>

<complexType name="Price">
    <simpleContent>
        <restriction base="double">
            <attribute name="currency" type="string"/>
        </restriction>
    </simpleContent>
</complexType>


</schema>

=== axelmate6/JD2018-12-10/src/by/it/kushnerov/jd02_07/users+att+xsd.xml
<?xml version="1.0" encoding="UTF-8" ?>
<users xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://jd02.kushnerov.by.it/somestring+att"
         xsi:schemaLocation="http://jd02.kushnerov.by.it/somestring+att users+att.xsd"
>
    <client nickname="pauk">
        <login>yaPauk</login>
        <email>yapauk@mail.ru</email>
        <password>11111</password>
        <name>Anatoliy</name>
        <surname>Metzengendler</surname>
        <phone>180011111</phone>
        <creditcard>1234567890</creditcard>
        <bookings max="100">
            <booking>
                <description>
                    Apartments for family with kids
                </description>
                <floor>5</floor>
                <rooms>4</rooms>
                <days>14</days>
                <price>10000.0</price>
            </booking>
        </bookings>
    </client>
    <client nickname="boss">
        <login>b0ss</login>
        <email>b0ss@mail.com</email>
        <password>aaaaaaa</password>
        <name>Chance</name>
        <surname>Morris</surname>
        <phone>1800133769</phone>
        <creditcard>0987654321</creditcard>
        <bookings max="100">
            <booking>
                <description>
                    Apartments near the restaurant
                </description>
                <floor>1</floor>
                <rooms>2</rooms>
                <days>3</days>
                <price>4666.1</price>
            </booking>
        </bookings>
    </client>
</users>
